import type { Metadata } from "next";
import { Coda, Nunito, Roboto } from "next/font/google";
import "./globals.css";
import { StitchesRegistry } from "./stitches-registry";

const coda = Coda({
  variable: "--font-coda",
  subsets: ["latin"],
  weight: ["400", "800"],
});

const nunito = Nunito({
  variable: "--font-nunito",
  subsets: ["latin"],
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${coda.variable} ${nunito.variable} ${roboto.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <StitchesRegistry>{children}</StitchesRegistry>
      </body>
    </html> 
  );
}
